src/main/java/com/uid2/operator/Main.java
src/main/java/com/uid2/operator/service/IUIDOperatorService.java
src/main/java/com/uid2/operator/service/UIDOperatorService.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

- Fixed the integer overflow when calculating valid till millis
- Change token/refresh endpoint to validate the refresh token is still valid
- Removed deprecated token/refresh-back endpoint

Fix up the validity time inside refresh token.

---

src/main/java/com/uid2/operator/service/UIDOperatorService.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

- remove the setting to have this configurable

Enforce checking refresh token expiry

---

src/main/java/com/uid2/operator/service/V2EncryptedTokenEncoder.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/main/resources/com.uid2.core/test/keys/keys.json
src/test/java/com/uid2/operator/TokenEncodingTest.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

Use refresh key to encrypt refresh token. Hide refresh key when responding to key query.

Use refresh key to encrypt refresh token. Hide refresh key when responding to key query.

---

scripts/aws/conf/prod-config.json
scripts/aws/entrypoint.sh

sync newly added config fields with upstream

Aws sync new configs

---

Makefile.nitro
scripts/aws/Dockerfile
scripts/aws/entrypoint.sh
scripts/aws/load_config.py
scripts/aws/proxies.nitro.yaml
scripts/aws/start.sh
scripts/aws/stop.sh
scripts/aws/uid2operator.service

Load secret/config from secrets manager instead of user data.
New pipe (inside-out):
- enclave /etc/paths: 127.0.0.1 secretsmanager.$REGION.amazonaws.com
- enclave vsockpx: 127.0.0.1:443 -> vsock 3:3308
- host https-proxy: vsock -1:3308 -> secretsmanager.$REGION.amazonaws.com 443

Uid2 88 aws read config from secret manager

---

scripts/aws/README.md

update aws deployment guide

---

src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/TransparentConsentTest.java

- Move TCF check logic details out of tokenGenerateV2 handler
- Remove an unused Println in unit test

TCF check follow up

---

Makefile.nitro
scripts/aws/conf/logback.loki.xml

[Change Note]
- loki_enabled config field now works for AWS enclaved operator
- change minimum log level from DEBUG to INFO in AWS enclaved operator

Fix loki override

---

pom.xml

creating release 1.11.0 to deploy tcf_consent_string change to EU

create a new release

---

scripts/aws/conf/integ-euid-config.json
scripts/aws/conf/integ-uid2-config.json
scripts/azure/conf/integ-config.json
scripts/azure/conf/prod-config.json
scripts/gcp/README.md
scripts/gcp/conf/integ-config.json
scripts/gcp/conf/prod-config.json

Update the config for aws integration, azure and gcp

Updated the deploy docs

---

pom.xml
src/main/java/com/uid2/operator/model/IdentityMapPolicy.java
src/main/java/com/uid2/operator/model/MapRequest.java
src/main/java/com/uid2/operator/model/MappedIdentity.java
src/main/java/com/uid2/operator/service/IUIDOperatorService.java
src/main/java/com/uid2/operator/service/UIDOperatorService.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
src/test/java/com/uid2/operator/benchmark/BenchmarkRunner.java
src/test/java/com/uid2/operator/benchmark/IdentityMapBenchmark.java

Changes:
1. deprecate UIDOperatorService.map method
2. create UIDOperatorService.identityMap method and MapRequest (similar to IdentityRequest)
3. add microbenchmark to estimate the performance impact

New identityMap API with micro benchmark

---

Dockerfile.nitro.builder
pom.xml
src/main/java/com/uid2/operator/Main.java

Repo name changes
- vsock-skeleton-key --> uid2-aws-enclave-vsockproxy
- nsm-java --> uid2-attestation-aws
- enclave-attestation-api --> uid2-attestation-api

update repo name

---

conf/local-config.json
src/main/java/com/uid2/operator/monitoring/TokenResponseStatsCollector.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

1. Moving cstg params to config file so we can be ready to deploy to integ with different set of param values without further code changes and not immediately relying on Ian's other PRs
2. Added CSTG Metric

Syw move cstg settings into config file

---

scripts/gcp-oidc/README.md

Updated the GCP OIDC read me file.
You could copy the file content and preview in https://markdownlivepreview.com/

update gcp readme

---

src/main/java/com/uid2/operator/monitoring/TokenResponseStatsCollector.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

added handling and tests for
- bad encrypted payload (not base64 or decryption fails)
- bad iv, wrong length
- bad iv, not base 64
- bad subscription id
- bad public key
- missing required request json field

Ian UID2-1684 cstg input validation

---

scripts/gcp-oidc/README.md

Add instruction to enable APIs.

Refine GCP-OIDC readme

---

scripts/gcp-oidc/terraform/.terraform.lock.hcl
scripts/gcp-oidc/terraform/README.md
scripts/gcp-oidc/terraform/main.tf
scripts/gcp-oidc/terraform/terraform.tfvars
scripts/gcp-oidc/terraform/variables.tf

1. Put `ssl` `private_key` `certificate` to input optional variable, if specified, we will create cert and enable ssl on LB.
2. Do not use http_redirect, use http_forward instead (by default true).

refine ssl template

---

.github/workflows/publish-gcp-oidc-enclave-docker.yaml
.gitignore
pom.xml

Verified by https://github.com/IABTechLab/uid2-operator/actions/runs/6308781243/job/17127503278

Auth GAR by workload_identity_provider

---

scripts/gcp-oidc/README.md
scripts/gcp-oidc/terraform/README.md
scripts/gcp-oidc/terraform/main.tf
scripts/gcp-oidc/terraform/variables.tf

Note: we will not update env input `API_TOKEN_SECRET_NAME` for now.

Replace "api_token" wording with "operator_key" in doc

---

scripts/aws/EUID_CloudFormation.template.yml
scripts/aws/UID_CloudFormation.template.yml

Remove VPC creation logic, following https://aws.amazon.com/blogs/awsmarketplace/cloudformation-templates-101-for-sellers-in-aws-marketplace/

Remove VPC creation bit, follow recommended practices

---

src/main/java/com/uid2/operator/monitoring/TokenResponseStatsCollector.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java

UID2-2094 Add token response metric recording when cstg endpoint processing fails some checks

---

src/main/java/com/uid2/operator/IdentityConst.java
src/main/java/com/uid2/operator/service/UIDOperatorService.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
src/test/java/com/uid2/operator/benchmark/BenchmarkCommon.java

[UID2-2083](https://atlassian.thetradedesk.com/jira/browse/UID2-2083)

fix example emails for validation and optout

---

src/main/java/com/uid2/operator/IdentityConst.java
src/main/java/com/uid2/operator/service/UIDOperatorService.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

Note that cstg refresh behavior is already tested by UIDOperatorVerticleTest#cstgOptedOutTest

token generate makes opt-opt token for old participant using policy=0

---

.github/workflows/e2e-azure-cc-enclave.yaml
e2e/prepare_azure_cc_artifacts.sh
e2e/start_azure_cc_enclave.sh
e2e/stop_azure_cc_enclave.sh

1. Address the ResourceGroup update.
2. The script that generate CCE policy has been modified, we can not refer it directly. Move the logic to `e2e/prepare_azure_cc_artifacts.sh`

Fix Azure E2E

---

src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

This PR is just enhancing some tests to meet the requirements of UID2-2113. I've added some comments in that ticket with more details - as many tests were already there.

UID2-2113 Make sure that token/refresh will generate an ad token version that respects advertising_token_v4_percentage

---

pom.xml
src/main/java/com/uid2/operator/service/SecureLinkValidatorService.java
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
src/test/java/com/uid2/operator/service/SecureLinkValidatorServiceTest.java

Added role validation for service links.
Tested
- Trying to validate a service link with the given role should return true
- Trying to validate a service link without the given role should return false

sch-UID2-2555-role-validation-for-service-links-in-operator

---

.github/workflows/run-e2e-tests-on-operator.yaml

Tested working for GCP operator: https://github.com/IABTechLab/uid2-operator/actions/runs/7444798695/job/20265027484
Tested the pipeline still works for public operator: https://github.com/IABTechLab/uid2-operator/actions/runs/7454713817/job/20282551433
Please review in order of:
* https://github.com/IABTechLab/uid2-e2e/pull/6
* https://github.com/IABTechLab/uid2-shared-actions/pull/48
* https://github.com/IABTechLab/uid2-operator/pull/315

UID2-2339 create test pipeline for gcp

---

.github/workflows/publish-gcp-oidc-enclave-docker.yaml

Success run: https://github.com/IABTechLab/uid2-operator/actions/runs/7456663433

Add E2E test as a part of the gcp publish pipeline

---

.github/workflows/publish-azure-cc-enclave-docker.yaml
.github/workflows/run-e2e-tests-on-operator.yaml

Please review in order of:
1. https://github.com/IABTechLab/uid2-operator/pull/329
2. https://github.com/IABTechLab/uid2-shared-actions/pull/50
3. https://github.com/IABTechLab/uid2-operator/pull/328
I’ve tested it working: 
- As an individual E2E task: https://github.com/IABTechLab/uid2-operator/actions/runs/7536390454/job/20513736679
- As a part of the publishing azure operator pipeline: https://github.com/IABTechLab/uid2-operator/actions/runs/7535436593

UID2-2340 Add test pipeline for Azure

---

pom.xml
src/main/java/com/uid2/operator/store/OptOutCloudStorage.java

Update shared to allow enforce jwt

---

conf/local-config.json
conf/local-e2e-docker-public-config.json
conf/local-e2e-private-config.json
conf/local-e2e-public-config.json
conf/validator-latest-e2e-docker-public-config.json
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/ExtendedUIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

The logs look like: 
`InvalidHttpOrigin: site MegaTest Site (123): http://localhosk345678ljkhbjklnjkbjjkkjn.com, http://localhosk345678ljkhbjklnjkbjn.com, http://localhosk345n.com | site TestCorp Site (124): http://localhos.com, http://localhosk.com, http://localhoskl.com`

UID2-2165 Log origin field for InvalidHttpOrigin errors

---

.github/actions/build_aws_eif/action.yaml
.github/workflows/e2e-azure-cc-enclave.yaml
.github/workflows/publish-all-operators.yaml
.github/workflows/publish-aws-nitro-enclave-docker.yaml
.github/workflows/publish-azure-cc-enclave-docker.yaml
.github/workflows/publish-gcp-oidc-enclave-docker.yaml
.github/workflows/publish-public-operator-docker-image.yaml
pom.xml
scripts/azure-cc/deployment/generate-deployment-artifacts.sh
scripts/gcp-oidc/generate-deployment-artifacts.sh

Remove the enclave Ids from the deployment artifacts and add them as stand alone artifacts.
Test runs:
https://github.com/IABTechLab/uid2-operator/actions/runs/8336812264
https://github.com/IABTechLab/uid2-operator/actions/runs/8336809413
https://github.com/IABTechLab/uid2-operator/actions/runs/8336807303
https://github.com/IABTechLab/uid2-operator/actions/runs/8336806028

Update output manifests

---

.github/workflows/publish-all-operators.yaml
.github/workflows/publish-aws-nitro-enclave-docker.yaml
.github/workflows/publish-azure-cc-enclave-docker.yaml
.github/workflows/publish-gcp-oidc-enclave-docker.yaml
.github/workflows/publish-public-operator-docker-image.yaml
pom.xml
scripts/gcp-oidc/generate-deployment-artifacts.sh

Standardising the names of the artifacts across all the operators.
Test builds:
https://github.com/IABTechLab/uid2-operator/actions/runs/8351757407
https://github.com/IABTechLab/uid2-operator/actions/runs/8351754602
https://github.com/IABTechLab/uid2-operator/actions/runs/8351752623
https://github.com/IABTechLab/uid2-operator/actions/runs/8351749551
Will need another test once merged.

Manifest name updates

---

.github/actions/build_aws_eif/action.yaml
.github/workflows/publish-aws-nitro-enclave-docker.yaml

Successful run: https://github.com/IABTechLab/uid2-operator/actions/runs/8428783502

Separate UID2 and EUID EIF build steps

---

.github/workflows/publish-aws-nitro-enclave-docker.yaml

Reverts IABTechLab/uid2-operator#453

Revert "Separate UID2 and EUID EIF build steps"

---

scripts/gcp-oidc/terraform/main.tf

Tested it witih non debug mode in integ, confirmed setting the correct url

UID2-3216 Set core and optout base url based on var.uid_deployment_env

---

.github/actions/build_aws_eif/action.yaml
.github/workflows/publish-aws-nitro-enclave-docker.yaml
pom.xml

Successful run: https://github.com/IABTechLab/uid2-operator/actions/runs/9755698873

UID2-3699 fix GitHub runner oos issue

---

.github/workflows/publish-azure-cc-enclave-docker.yaml
.github/workflows/run-e2e-tests-on-operator.yaml
scripts/azure-cc/deployment/generate-deployment-artifacts.sh

Successful run: https://github.com/IABTechLab/uid2-operator/actions/runs/10153712454/job/28077708892
Please review these two PR together:
* https://github.com/IABTechLab/uid2-operator/pull/823
* https://github.com/IABTechLab/uid2-shared-actions/pull/115

UID2-3857 Add changes for downgrading azure cli

---

.github/actions/build_ami/action.yaml
.github/workflows/build-uid2-ami.yaml
.github/workflows/publish-all-operators.yaml

Revert step names.
Always save the AMI artifacts
Change the name of the AMI artifacts

Revert step names

---

Makefile.eif
pom.xml
scripts/aws/conf/logback-debug.xml
scripts/aws/eks-pod/entrypoint.sh
scripts/aws/eks-pod/proxies.host.yaml
scripts/aws/eks-pod/sockd_eks.conf
scripts/aws/entrypoint.sh
scripts/aws/proxies.host.yaml
scripts/aws/proxies.nitro.yaml
scripts/aws/sockd.conf

This branch is deletion protected, and should not be merged into main. It is for building aws-nitro snapshot versions only.

nitro enclave debug

---

Makefile.eif
scripts/aws/pipeline/amazonlinux2023.Dockerfile
scripts/aws/pipeline/aws_nitro_eif.sh

- Clean up unneeded files/resources after they no longer needed to reduce disk space usage and reducing the risk of github runner running out of disk space

UID2-4429 More efficient disk space utilisation when building operator enclaves

---

pom.xml
src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java

Update share uid2 lib to 8.0.9, which added site name into metrics
Test
Unit Test

Xuy UI d2 2578 update share lib to add site name to metrics

---

.trivyignore
conf/integ-config.json
conf/local-e2e-docker-private-config.json
conf/local-e2e-docker-public-config.json
conf/local-e2e-private-config.json
conf/local-e2e-public-config.json
conf/validator-latest-e2e-docker-public-config.json
pom.xml
scripts/aws/conf/euid-integ-config.json
scripts/aws/conf/euid-prod-config.json
scripts/aws/conf/uid2-integ-config.json
scripts/aws/conf/uid2-prod-config.json
scripts/azure-cc/conf/integ-uid2-config.json
scripts/azure-cc/conf/prod-uid2-config.json
scripts/gcp-oidc/conf/integ-config.json
scripts/gcp-oidc/conf/prod-config.json
src/main/java/com/uid2/operator/service/ConfigRetrieverFactory.java
src/test/java/com/uid2/operator/ConfigServiceTest.java

- Change ConfigRetrieverFactory to parse url into URI for http store
- Update all 'runtime_config_store' 'config' objects with http type to contain 'url' field only

Change remote_config_store config to url 

---

Dockerfile
scripts/azure-cc/Dockerfile
scripts/gcp-oidc/Dockerfile

Reverts IABTechLab/uid2-operator#1385

Revert "Fix CVE-2024-12797"

---

scripts/aws/EUID_CloudFormation.template.yml

fixed scripts/aws/EUID_CloudFormation.template.yml token secret format

xuy-UID2-4989-p-operator-euid-e2e

---

.trivyignore

Added back CVE-2024-57699 to .trivyignore

---

src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

Set default AllowLegacyAPIProp value to false

---

pom.xml
scripts/azure-aks/deployment/generate-deployment-artifacts.sh

- Add error checking.
- Fix path to generate.py.
- Some sed commands should have been on ${INPUT_DIR}/generated.rego.
- Collapse multiple sed commands into one for simpler error checking.
Test run: https://github.com/IABTechLab/uid2-operator/actions/runs/14119706651/job/39557670292

Fix AKS enclave ID

---

Dockerfile
pom.xml

create a directory for prestop hook to write to and update shared version

update dockerfile to include directoy for prestop hook

---

1
src/main/java/com/uid2/operator/monitoring/StatsCollectorVerticle.java
src/test/java/com/uid2/operator/EUIDOperatorVerticleTest.java
src/test/java/com/uid2/operator/StatsCollectorVerticleTest.java
src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java

Plan to squash and merge due to long commit history

remove v1 related conditional check code
