- src/main/java/com/uid2/operator/Main.java
- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
This will allow producing refresh tokens with sensible expiry before enforcing the check. Temporarily configurable for dev purposes: config will be eventually removed.
> Check refresh token expiry based on config (default: false)

- conf/local-config.json
- js/Makefile
- js/uid2-sdk-1.0.0/.eslintignore
- js/uid2-sdk-1.0.0/.eslintrc.js
- js/uid2-sdk-1.0.0/.gitignore
- js/uid2-sdk-1.0.0/autoRefresh.test.js
- js/uid2-sdk-1.0.0/basic.test.js
- js/uid2-sdk-1.0.0/compatibility.test.js
- js/uid2-sdk-1.0.0/mocks.js
- js/uid2-sdk-1.0.0/options.test.js
- js/uid2-sdk-1.0.0/package-lock.json
- js/uid2-sdk-1.0.0/package.json
- js/uid2-sdk-1.0.0/setupJest.js
- src/main/java/com/uid2/operator/Main.java
- src/main/java/com/uid2/operator/model/IdentityTokens.java
- src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
- src/main/java/com/uid2/operator/service/ITokenEncoder.java
- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/main/java/com/uid2/operator/service/V2EncryptedTokenEncoder.java
- src/main/java/com/uid2/operator/vertx/ClientVersionCapturingHandler.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
- static/js/uid2-sdk-1.0.0.js
- added v1 of the client SDK
- added npm/jest based unit tests for the client SDK
- change operator v1/token/generate and v1/token/refresh endpoints return expiry timestamps for refresh and advertising tokens, timestamp from which the client is expected to start refreshing
- added a counter metric to collect versions of client SDK hitting operator endpoints
> UID2 JS Client SDK v1

- js/uid2-sdk-1.0.0/async.test.js
- js/uid2-sdk-1.0.0/basic.test.js
- static/js/uid2-sdk-1.0.0.js
- reset the identity state to unavailable
- reject outstanding promises
> Fixes for JS SDK v1 disconnect method

- pom.xml
- src/test/java/com/uid2/operator/TokenEncodingTest.java
* Update TokenEncodingTest.testRefreshTokenEncoding considering extra valid minute added by encoder
* Add surefire arg to run test using UTF-8 as default charset
> Enable and fix a couple junit vintage tests

- conf/local-config.json
- src/main/java/com/uid2/operator/model/IdentityScope.java
- src/main/java/com/uid2/operator/model/IdentityType.java
- src/main/java/com/uid2/operator/model/OperatorType.java
- src/main/java/com/uid2/operator/model/RefreshResponse.java
- src/main/java/com/uid2/operator/model/RefreshToken.java
- src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
- src/main/java/com/uid2/operator/service/EncryptionHelper.java
- src/main/java/com/uid2/operator/service/TokenUtils.java
- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/main/resources/com.uid2.core/test/keys/keys.json
- src/test/java/com/uid2/operator/TokenEncodingTest.java
- config controls whether ID v2 or v3 is to be generated for UID2 emails
- config controls whether v2 or v3 advertising/refresh tokens are to be generated
- enable parsing both v2 and v3 tokens
> IDv3 support for generating and parsing tokens and UID string

- js/uid2-sdk-1.0.0/basic.test.js
- js/uid2-sdk-1.0.0/package-lock.json
- static/js/uid2-sdk-1.0.0.js
Presently, if `googletag` is not defined on the window when the uid2 js script is loaded, the `encryptedSignalProviders.push` call is not made and therefore the `collectorFunction` is never called.
In this situation where `googletag` is not defined, you can define`window.googletag.encryptedSignalProviders` with the desired object and googletag will pick it up when its js loads. This PR implements that change.
> Allow setupGoogleTag in JS SDK to be called prior to googleTag loading

- js/euid-sdk-1.0.0/basic.test.js
- js/euid-sdk-1.0.0/compatibility.test.js
- js/uid2-sdk-1.0.0/autoRefresh.test.js
- js/uid2-sdk-1.0.0/basic.test.js
- js/uid2-sdk-1.0.0/compatibility.test.js
- js/uid2-sdk-2.0.0/autoRefresh.test.js
- js/uid2-sdk-2.0.0/basic.test.js
- js/uid2-sdk-2.0.0/compatibility.test.js
- static/js/euid-sdk-1.0.0.js
- static/js/uid2-sdk-1.0.0.js
- static/js/uid2-sdk-2.0.0.js
According to UnifiedID2/uid2docs#42's feedback from @elenaTTD, I updated the callback naming to make it consistent between doc and real code behavior.
SDK v1 actually has same inconsistency between doc and codes. Should v1's SDK code be renamed too? 
Thank you.
> Update SDK callback parameter naming

- src/main/java/com/uid2/operator/monitoring/StatsCollectorHandler.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/StatsCollectorHandlerTest.java
- Avoid null exception if no auth provided and specific (static) path does not exist.
- Collect stats for existing static paths too (previously they were not collected).
> Fix stats collection for unauthenticated non-existing static endpoints.

- .github/workflows/validate-image.yaml
Running the tests in parallel results in contention on the test port.
Relates to UID2-641, not UID2-577
> Added needs statements to require jobs to run serially to stop port contention

- src/main/java/com/uid2/operator/model/IdentityRequest.java
- src/main/java/com/uid2/operator/model/IdentityTokens.java
- src/main/java/com/uid2/operator/model/TokenGeneratePolicy.java
- src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
- src/main/java/com/uid2/operator/service/ResponseUtil.java
- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/main/java/com/uid2/operator/service/V2RequestUtil.java
- src/main/java/com/uid2/operator/store/IOptOutStore.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/main/java/com/uid2/operator/vertx/V2PayloadHandler.java
- src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
1. v2/token/generate accepts an optional parameter in body "policy" (integer). 0 = old behavior, 1 = respects opt out record
2. trying to generate a token for a user who opted out will return empty string as advertising token
> New token-generate parameter to respect earlier optout records

- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
- Always enforce the special identities optout/optin status regardless what the optout store would state.
- This enforcement applied to token/generate, token/client-generate and token/refresh
- All optout check goes thru UID2OperatorService.hasGlobalOptOut so the special identities like above are handled in this method now
> Syw UID2-1224 special email opt out handling

- scripts/gcp-oidc/conf/default-config.json
to reserve some CPU resources for background jobs
> Set GCP OIDC enclave service instances to 12

- src/main/java/com/uid2/operator/Main.java
I want this to make testing alerts easier, but could be useful in other contexts.
(Eventually these configs will come from Core)
> make refresh times to Core configurable

- .github/workflows/publish-gcp-oidc-enclave-docker.yaml
- pom.xml
* Push Docker image to both GitHub Registry and GCP Registry, they use the same image digest. It means when create a new enclave ID, you can still go to the GitHub packages page to find the digest.
* Currently it uses test project, should switch to production once it's ready
> Push image to GCP Registry

- scripts/gcp-oidc/terraform/README.md
- scripts/gcp-oidc/terraform/main.tf
- scripts/gcp-oidc/terraform/variables.tf
- Make `uid_deployment_env` a required input.
- Remove `uid_machine_type` input, it will be decided based on `uid_deployment_env`
> change terraform variables: env and machine type

- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
If a user has opted out after token generation, we should return an opted out token upon refresh.
> Return opted out token on CSTG refresh

- src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
- src/main/java/com/uid2/operator/service/V2RequestUtil.java
This PR fixes some mismatches that arose from https://github.com/IABTechLab/uid2-operator/pull/259
- Catch `IllegalArgumentException` in `parseRefreshRequest`
- Throw `ClientInputValidationException` in `decodeRefreshTokenV3` when `this.keyManager.getKey(keyId)` returns null. Also log out the `keyId`
> Fix status codes

- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
This PR affects POST `/v1/identity/map` and POST `/v2/identity/map` endpoints. For both 
- Ignore `policy` and `optout_check` parameters
- Enforece optout check on the identifiers and reply with identifier in unmapped section
No changes to 
- GET `/v1/identity/map`
- GET `/identity/map` (Deprecated)
| Scenario | Result | Test Name | Endpoint |
|--------|--------|--------|--------|
| Request body contains optout or policy parameter | Ignore parameter and enforce optout check | `identityMapRespectOptOutOption()`, `identityMapNewClientWrongPolicySpecified()`| POST `/v1/identity/map`|
|||`identityMapRespectOptOutOption()`, `identityMapNewClientWrongPolicySpecified()`| POST `/v2/identity/map`|
| Request body doesn't contain optout or policy parameter | Still enforce optout check  | …
> [UID2-2204] Ignore policy param for identity/map

- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
Its hard to write a unit test for this because to trigger the code flow I need to mock the `RoutingContext` . Specifically, 
```
rc.get(SecureLinkValidatorService.SERVICE_LINK_NAME, ""); // and
rc.get(SecureLinkValidatorService.SERVICE_NAME);
```
which is not possible right now, because the `RoutingContext` object is not accessible for mocking
> [UID2-2148] Use service name + link for metric key

- src/main/java/com/uid2/operator/model/IdentityTokens.java
- src/main/java/com/uid2/operator/monitoring/TokenResponseStatsCollector.java
- src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
- src/main/java/com/uid2/operator/service/ResponseUtil.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
This pull request adds the `advertising_token_version` label to the `uid2_token_response_status_count` metric.
It also removes the second layer of caching of the counter - Micrometer already does this for us. Having to update the `TokenResponseKey` class every time we add a label complicates things.
> Record advertising token version in uid2_token_response_status_count metric

- .github/workflows/publish-all-operators.yaml
- .github/workflows/publish-public-operator-docker-image.yaml
- pom.xml
Parent pipeline that creates the version number, calls each of the operator pipelines and builds them.
It then collects the artifacts.
Tested on a branch with only calling the public operator build as that is what is currently ready.
Will need to be tested once merged to main.
> Build all Operators pipeline

- .github/workflows/publish-all-operators.yaml
- pom.xml
Adding scanning early to detect errors early in the pipeline. Scanning will be done again on the images. This is only scanning the code.
Tested on a branch.
Will need to be tested once merge.
> UID2-2343 Add trivy scanning 

- Dockerfile.nitro.builder
- Makefile.nitro
This pull request makes the AWS private operator build use `scripts/aws/conf/default-config.json` instead of `conf/default-config.json`.
This works by explicitly copying the required config files into `build/conf`.
Previously we were including all files from `conf` into `build/conf`.
This meant:
- We were including `conf/default-config.json` instead of `scripts/aws/conf/default-config.json`.
- We had extra code to overwrite `build/conf/logback.loki.xml` (from `conf/logback.loki.xml`) with `scripts/aws/conf/logback.loki.xml`
- We were including files not required by private operator (e.g. `local-e2e-public-config.json`)
> Fix AWS private operator default-config.json

- scripts/azure-cc/Dockerfile
- scripts/azure-cc/conf/integ-uid2-config.json
- scripts/azure-cc/deployment/operator.json
- scripts/azure-cc/entrypoint.sh
Please review in order of:
1. https://github.com/IABTechLab/uid2-operator/pull/329
2. https://github.com/IABTechLab/uid2-shared-actions/pull/50
3. https://github.com/IABTechLab/uid2-operator/pull/328
I’ve tested it working: 
- As an individual E2E task: https://github.com/IABTechLab/uid2-operator/actions/runs/7536390454/job/20513736679
- As a part of the publishing azure operator pipeline: https://github.com/IABTechLab/uid2-operator/actions/runs/7535436593
> UID2-2340 Allow override for `enforce_https`

- scripts/azure-cc/entrypoint.sh
- scripts/gcp-oidc/entrypoint.sh
This will break the e2e testing, but is required to keep the operators secure. Another approach will be needed to enable end to end testing
> Removed the ability to set the urls from the environment

- .github/workflows/publish-all-operators.yaml
- .github/workflows/run-e2e-tests-on-operator.yaml
* https://github.com/thetradedesk/git-restore-mtime-action/pull/2, this is to update node version for thetradedesk/git-restore-mtime-action@v1.2, also pulled in the latest change from chetan/git-restore-mtime-action@v2
Once the above is merged and released, I will make the related update in below to get rid of all the warnings (except for azure/login@v1):
- https://github.com/IABTechLab/uid2-operator/pull/362
- https://github.com/IABTechLab/uid2-shared-actions/pull/70
> UID2-2861 Fix-github-warnings

- .github/workflows/publish-aws-nitro-enclave-docker.yaml
- pom.xml
Saving the EIF files as separate artifacts means that only the required files are downloaded when building the AMI.
Test run:
https://github.com/IABTechLab/uid2-operator/actions/runs/8319307678
This will need to be tested as part of a full release
> Save eif for uid2 and euid

- scripts/gcp-oidc/Dockerfile
- scripts/gcp-oidc/README.md
- scripts/gcp-oidc/terraform/main.tf
Tested it working with "confidential-space" family: (https://console.cloud.google.com/logs/query;query=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%224236641475715379579%22;cursorTimestamp=2024-04-16T05:43:59.110328Z;duration=PT1H?orgonly=true&project=uid2-developer-project&supportedpurview=organizationId)
> UID2-2071 Enable log redirect

- pom.xml
- src/main/java/com/uid2/operator/model/CstgRequest.java
- src/main/java/com/uid2/operator/monitoring/TokenResponseStatsCollector.java
- src/main/java/com/uid2/operator/service/ResponseUtil.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/main/resources/com.uid2.core/test/sites/sites.json
- src/test/java/com/uid2/operator/ExtendedUIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
- App name is sent as part of the request payload.
- App name is part of the AAD.
- App name check is case insensitive.
- Invalid app names are logged together with invalid origins.
- App name check is controlled by the existing feature flag `client_side_token_generate_domain_name_check_enabled`.
> CSTG: Validate app name

- conf/local-config.json
- conf/local-e2e-docker-public-config.json
- conf/local-e2e-public-config.json
- conf/validator-latest-e2e-docker-public-config.json
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/main/resources/com.uid2.core/test/keyset_keys/keyset_keys.json
- src/main/resources/com.uid2.core/test/keysets/keysets.json
- src/main/resources/com.uid2.core/test/sites/sites.json
- src/test/java/com/uid2/operator/ExtendedUIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
Pending change : Updating shared version in pom.xml
Functionality is controlled behind flag `key_sharing_endpoint_provide_app_names`. The flag is disabled if the config is absent. In local config files, the flag is enabled. Also cleaned up old flag `key_sharing_endpoint_provide_site_domain_names`.
Example Request Response for bidstream
```
<edit Updated response below>
curl --location --request POST 'http://127.0.0.1:8080/v2/key/bidstream' \
--header 'Authorization: Bearer API_TOKEN' \
--data ''
RESPONSE
{
"body": {
"max_bidstream_lifetime_seconds": 3610,
"identity_scope": "UID2",
"allow_clock_skew_seconds": 1800,
"keys": [
{
"id": 5,
"created": 1609459200,
"activates": 1609469200,
"expires": 4088629662,
"secret": "<secret>"
},
{
"id": 11,
"created": 1713225363,
"activates": 1713250563, …
```
> [UID2-2831] Send Site's app name in key/sharing  and key/bidstream endpoints

- scripts/azure-cc/deployment/operator.json
Tested with a manual deploy. Containers started first time, and didn't see any UnknownHost exceptions
> Gave the skr container more cpu and memory

- src/main/java/com/uid2/operator/store/CloudSyncOptOutStore.java
- Number of advertising IDs.
- Time to query optout timestamp by advertising ID.
- Time to query optout timestamp by first-level hash.
- Labelled by the Bloom filter's answer.
- Time to process delta files.
- Time to process partition files.
> Create new optout metrics

- conf/default-config.json
- conf/local-config.json
- conf/local-e2e-docker-public-config.json
- src/main/java/com/uid2/operator/Const.java
- src/main/java/com/uid2/operator/Main.java
- src/main/java/com/uid2/operator/store/CloudSyncOptOutStore.java
- src/main/java/com/uid2/operator/store/IOptOutStore.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
- src/test/java/com/uid2/operator/benchmark/BenchmarkCommon.java
- src/test/java/com/uid2/operator/store/OptOutStoreSnapshotTest.java
This method returns the earliest optout timestamp for a given advertising ID.
One commit is a workaround for an issue where calling `toPartition` on an empty heap throws an assertion error. This issue has laid dormant because we didn't have any tests covering `OptOutStoreSnapshot` until now. The workaround is to use `null` instead, so we need some extra checks.
Included are some small improvements:
- Use `sum` instead of `reduce` for clarity.
- Change type of `OptOutStoreSnapshot.fsLocal` from `ICloudStorage` to `DownloadCloudStorage` for easier testing.
- Pass a `Clock` to `OptOutStoreSnapshot` for easier testing.
> Add method OptOutStoreSnapshot.getAdIdOptOutTimestamp

- pom.xml
- src/main/java/com/uid2/operator/service/ResponseUtil.java
- src/main/java/com/uid2/operator/service/RoutingContextReader.java
- src/test/java/com/uid2/operator/service/ResponseUtilTest.java
Deployed to integ and tested it working: [dashboard](https://dash.uidapi.com/explore?orgId=1&left=%7B%22datasource%22:%22dADfYKrGk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D%5C%22uid2-operator%5C%22,%20host%3D%5C%22uid2-operator-integ-6bcbb4f66d-wjf7x%5C%22%7D%20%7C%3D%20%60%2Ftoken%2Frefresh%60%20%7C%3D%20%60%5C%22statusCode%5C%22:400%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22dADfYKrGk%22%7D,%22editorMode%22:%22builder%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22dADfYKrGk%22%7D,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221716793816279%22,%22to%22:%221716794192488%22%7D%7D)
> UID2-3406 Add logging for origin and referer to 4xx warnings

- src/main/java/com/uid2/operator/monitoring/TokenResponseStatsCollector.java
- src/main/java/com/uid2/operator/service/ResponseUtil.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/main/java/com/uid2/operator/vertx/V2PayloadHandler.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
```
uid2_token_response_status_count_total{advertising_token_version="V2", application="uid2-operator", cstg="true", instance="host.docker.internal:9080", job="services", platformType="HasOriginHeader", site_id="123", site_name="MegaTest Site", token_endpoint="ClientSideTokenGenerateV2", token_response_status="Success"}
uid2_token_response_status_count_total{advertising_token_version="null", application="uid2-operator", cstg="true", instance="host.docker.internal:9080", job="services", platformType="InApp", site_id="123", site_name="MegaTest Site", token_endpoint="ClientSideTokenGenerateV2", token_response_status="InvalidAppName"}
```
Slack discussions are here: https://thetradedesk.slack.com/archives/C051ELQ8JAC/p1716760305149009
Add the platformType for `/token/client-generate`,` …
> Add metrics info for Mobile CSTG

- scripts/aws/EUID_CloudFormation.template.yml
- scripts/aws/UID_CloudFormation.template.yml
Added egress on port 53 UDP for dns.
There was a change in the nitro-cli vsock-proxy that changed the way it does name resolution: https://github.com/aws/aws-nitro-enclaves-cli/releases/tag/v1.3.1
To support this, the EC2 instance needs to be able to do dns lookup. Adding egress on port 53 allows this.
Also added 2 new machine types: m6i, r6i.
> Added machine type and egress rule

- .github/workflows/run-e2e-tests-on-operator.yaml
- scripts/aws/eks/deployment_files/deployment.yaml
Please review these two PRs together:
* https://github.com/IABTechLab/uid2-operator/pull/889
* https://github.com/IABTechLab/uid2-shared-actions/pull/117
Checked working:
> UID2-3783 Add files and scripts for running EKS e2e tests

- pom.xml
- scripts/aws/entrypoint.sh
Refactored the entrypoint to remove the duplicate call to getConfig
Tested in Test and operator starts correctly. Checked the logs, and the configuration is not echoed to the logs, as expected.
> Refactor enclave entrypoint

- pom.xml
- src/main/java/com/uid2/operator/Main.java
- src/main/java/com/uid2/operator/vertx/OperatorShutdownHandler.java
- src/test/java/com/uid2/operator/OperatorShutdownHandlerTest.java
Tested with branch deploy. Ran in Integ and passed validation.
> Only shut the operator down when receiving an AttestationFailure response from Core

- pom.xml
- src/main/java/com/uid2/operator/monitoring/StatsCollectorHandler.java
- src/main/java/com/uid2/operator/monitoring/StatsCollectorVerticle.java
- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/main/java/com/uid2/operator/service/V2RequestUtil.java
- src/main/java/com/uid2/operator/store/CloudSyncOptOutStore.java
- src/main/java/com/uid2/operator/util/Tuple.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
- src/test/java/com/uid2/operator/V2RequestUtilTest.java
Refactors
- move test method out of UIDOperatorService.java
- moving error message string literals to constants
TODO
> Removing assertions from code and replacing with relevant exceptions

- scripts/aws/eks-pod/entrypoint.sh
- scripts/aws/entrypoint.sh
- scripts/aws/make_config.py
- scripts/aws/start.sh
- Avoid oversubscribing host and enclave
- Host: half cores to vsockpx
- Enclave: 2/3 cores to operator reactor vertices, 1/4 cores to vsockpx
> UID2-4430 Automatic allocation of cores to vsockpx and operator vertx

- src/main/java/com/uid2/operator/service/JsonParseUtils.java
- src/main/java/com/uid2/operator/service/ResponseUtil.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/main/java/com/uid2/operator/vertx/V2PayloadHandler.java
- src/test/java/com/uid2/operator/service/ResponseUtilTest.java
1. Refine response logging, client error, invalid http origin, and invalid app name responses are logged as info, other responses are still logged as warning.
2. Simplify and remove duplication of the message composing logic
The logging and sending response logic might be further separated into distinct functions, to scope the current MR, left to future optimization.
Test
Unit Test
> xuy-UID2-4341-change-log-level Refine response logging

- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/test/java/com/uid2/operator/EUIDOperatorVerticleTest.java
- src/test/java/com/uid2/operator/TokenEncodingTest.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
1. From an [PR ](https://github.com/IABTechLab/uid2-operator/pull/1180/files#diff-899d4736c54595d19fe3f5d5b0ab7739007365b694a2c9c66b445e5cf2013c29R666-R668)earlier, it's now only using Raw UID v3 format for UIDOperatorVerticleTest  which is wrong as we still use v2 Raw UID format for UID2 prod.
2. UIDOperatorVerticleTest was incorrectly using Raw UID Format v3 and fixing it requires fixing one of the unit tests 
3. renamed the variable/method useIdentityV3/identityV3Enabled to useRawUidV3/rawUidV3Enabled to be up to date with latest terminlogies
4. Improved TokenEncodingTest#testAdvertisingTokenEncodings to tests all combo's of raw UID and ad token versions
> Use correct raw UID version for UID2 UIDOperatorVerticleTest and rename identityV3Enabled to rawUidV3Enabled

- src/main/java/com/uid2/operator/Main.java
Add gauge for number of vertx service instances and event loop threads in Operator. This will allow us to allocate the appropriate number of CPUs to Operator to reduce latency.
> sch-UID2-4560 add gauge for number of processing request threads

- scripts/aws/ec2.py
- scripts/confidential_compute.py
**When IAM role is not attached** 
```
Dec 27 22:10:29 ip-172-31-30-140.ec2.internal systemd[1]: Starting uid2operator.service - Starter service for UID2 Operator Enclave...
Dec 27 22:10:30 ip-172-31-30-140.ec2.internal uid2operator[3424]: Running in us-east-1
Dec 27 22:10:30 ip-172-31-30-140.ec2.internal uid2operator[3424]: Failed starting up Confidential Compute. Please checks the logs for errors and retry
Dec 27 22:10:30 ip-172-31-30-140.ec2.internal uid2operator[3424]: E01: MissingInstanceProfile
Dec 27 22:10:30 ip-172-31-30-140.ec2.internal uid2operator[3424]: Visit https://unifiedid.com/docs/guides/operator-guide-aws-marketplace#uid2-operator-error-codes for more details
```
**When Secret manager does not exist**
```
Dec 27 22:17:10 ip-172-31-22-85.ec2.internal uid2operator[2530]: …
```
> Create custom exceptions and link it to website

- pom.xml
- src/main/java/com/uid2/operator/Main.java
Meter filter logic for path normalisation has been moved to Shared to be used across all apps.
> sch-UID2-4073 high level tests for path normalisation in metrics 

- scripts/gcp-oidc/Dockerfile
- scripts/gcp-oidc/terraform/main.tf
Currently, when debug mode is set, our validation process is unaware of it, and hence passes validation. However GCP attestation would fail when we are running debug in prod. 
Pass DEBUG_MODE to inside container to check and produce validation errors on start
> Pass DEBUG_MODE to container to allow for better error handling

- pom.xml
- scripts/aws/UID_CloudFormation.template.yml
- scripts/aws/ec2.py
- scripts/aws/sockd.conf
- scripts/confidential_compute.py
logs are stored at /var/log
-rw-r--r--. 1 root   root                294 Feb 18 22:04 vsock_proxy.log
-rw-r--r--. 1 root   root                386 Feb 18 22:04 socks_proxy.log
drwxrwxr-x. 2 root   ne                16384 Feb 18 22:04 nitro_enclaves
-rw-r--r--. 1 root   root                165 Feb 18 22:04 flask_config_server.log
-rw-------. 1 root   root            1208490 Feb 18 22:04 operator.log
The PR also fixed a json format bug:
before fix, secret returns : 
**{"core_base_url": https://core-integ.uidapi.com, "optout_base_url": https://optout-integ.uidapi.com,** "operator_key": "UID2-O-I-18-Fk6QJg.xxx", "service_instances": 6, "enclave_cpu_count": 6, "enclave_memory_mb": 24576, "environment": "integ", "debug_mode" : true}
after the fix:
{"core_base_url": …
> xyang-UID2-4369-enable-nitro-logging

- Dockerfile
- pom.xml
This unused arg causes the entire build context to be copied to
/app/conf, including 1.7G of Trivy cache files.
|              | Before | After | Saving |
|--------------|--------|-------|--------|
| Compressed   | 2.1GB  | 216MB | 90%    |
| Uncompressed | 4.36GB | 371MB | 91%    |
> Remove EXTRA_CONFIG build arg

- scripts/aws/EUID_CloudFormation.template.yml
Revert default urls for euid
( bug introduced in https://github.com/IABTechLab/uid2-operator/pull/1504)
> xuy-UID2-4989-p-operator-e2es revert fix default urls

- .github/workflows/run-e2e-tests-on-operator.yaml
- .trivyignore
* Added `target_environment` input to distinguish between `mock`, `integ` and `prod` tests
* `mock` tests retain current behaviour
* `integ` and `prod` tests have additional logic to support real environment testing
* HTTPS URLs, different operator keys, no need for Docker and bore
* Added `operator_shutdown` input to keep private operators running for extended manual testing
> Enhanced E2E pipeline to better support real env testing #164

- scripts/aws/UID_CloudFormation.template.yml
- scripts/aws/entrypoint.sh
/usr/sbin/syslog-ng --verbose
is only needed when operator has debug mode enabled
> Fix debug logs

- .github/workflows/run-e2e-tests-on-operator.yaml
Changes are based on https://github.com/IABTechLab/uid2-shared-actions/pull/168
> Updated E2E test pipeline

- scripts/aws/EUID_CloudFormation.template.yml
- scripts/aws/UID_CloudFormation.template.yml
Description:
Updated CFT template to comply with aws new version work flow.
Test:
Tested in UID and EUID region.
> xuy-UID2-5201-Update-CFT for aws market place

- scripts/azure-cc/Dockerfile
- scripts/gcp-oidc/Dockerfile
Updating eclipse-temurin to 21.0.7_6-jre-alpine-3.21 for GCP and Azure
> Fixing vulnerability CVE-2025-29087

- conf/default-config.json
- conf/docker-config.json
- conf/integ-config.json
- conf/local-config.json
- conf/local-e2e-docker-private-config.json
- conf/local-e2e-docker-public-config.json
- conf/local-e2e-private-config.json
- conf/local-e2e-public-config.json
- conf/validator-latest-e2e-docker-public-config.json
- pom.xml
- src/main/java/com/uid2/operator/Main.java
- src/main/java/com/uid2/operator/service/IUIDOperatorService.java
- src/main/java/com/uid2/operator/service/UIDOperatorService.java
- src/main/java/com/uid2/operator/store/CloudSyncOptOutStore.java
- src/main/java/com/uid2/operator/store/IOptOutStore.java
- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/ExtendedUIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorServiceTest.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
- src/test/java/com/uid2/operator/benchmark/BenchmarkCommon.java
Changes in this PR and [Shared PR](https://github.com/IABTechLab/uid2-shared/pull/457/files):
- Added instance ID configs for local Operators
- Initialised the UidInstanceIdProvider and passed it to where it's needed
- Attached UID-Instance-Id header to all requests made to Core and Opt Out
- Forwarded UID-Trace-Id header for logout requests
Tested locally in dev workspace:
- UID instance ID is being populated in headers in all requests to Core
- Core is receiving the instance ID and adding it to audit logs
> Add service instance ID and UID trace ID to core and opt out requests

- src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
- src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
Always use millisecond precision for ISO8601 timestamps in identity/buckets
> Always use millisecond precision for ISO8601 timestamps in identity/buckets
